<?php

namespace FredBradley\SOCS\Tests;

use Carbon\Carbon;
use Carbon\CarbonInterface;
use FredBradley\SOCS\Config;
use PHPUnit\Framework\TestCase;
use SimpleXMLElement;

class BaseTest extends TestCase
{
    protected CarbonInterface $startDate;
    protected CarbonInterface $endDate;
    protected Config $config;

    public function setUp(): void
    {
        $this->config = new Config();
        $this->startDate = Carbon::now()->subMonths(3);
        $this->endDate = Carbon::now()->addMonths(3);

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /** @test */
    public function true_is_true()
    {
        $this->assertTrue(true);
    }

    protected function isIterableXmlObject(SimpleXMLElement $result)
    {
        $this->assertIsObject($result);
        $this->assertIsIterable($result);
        $this->assertThat($result, self::isInstanceOf(SimpleXMLElement::class));
    }
}
