name: Tests

on: ['push', 'pull_request']

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        php: [ 8.2, 8.3 ]
        stability: [ prefer-lowest, prefer-stable ]

    name: P${{ matrix.php }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, libxml, mbstring, pcntl, bcmath, intl, exif, iconv, fileinfo, xsl, sodium, xml, json
          tools: composer:v2
          coverage: xdebug

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Tests
        env:
          SOCSAPIKEY: ${{ secrets.SOCSAPIKEY }}
          SOCSID: ${{ secrets.SOCSID }}
        run: ./vendor/bin/pest
