name: Bump version

on:
  push:
    branches:
      - master

jobs:
  releaseJob:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch to calculate changelog
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Calculate version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          create_annotated_tag: true
          tag_prefix: v
          dry_run: true

      - name: Get updated commit SHA
        run: echo "commit_id=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        id: updated_sha

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_sha: ${{ steps.updated_sha.outputs.commit_id }}
          default_bump: patch
          create_annotated_tag: true
          tag_prefix: v

      - name: Create Release
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ steps.tag_version.outputs.new_tag }} -t ${{ steps.tag_version.outputs.new_tag }} --generate-notes
